"""bind_jobs_to_trusted_policy_revision

Revision ID: 38268b7c5d67
Revises: cdafc9dd5a99
"""

import sqlalchemy as sa
from alembic import op

revision = "38268b7c5d67"
down_revision = "cdafc9dd5a99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_jobs", sa.Column("trusted_revision_hash", sa.String(length=64), nullable=False)
    )
    op.create_foreign_key(
        "fk_jobs_trusted_revision",
        "review_jobs",
        "guard_revisions",
        ["trusted_revision_hash"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_jobs_trusted_revision", "review_jobs", type_="foreignkey")
    op.drop_column("review_jobs", "trusted_revision_hash")
    # ### end Alembic commands ###
