"""initial_versioned_review_storage

Revision ID: cdafc9dd5a99
Revises:
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "cdafc9dd5a99"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accepted_output_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_accepted_output_cache_scope"), "accepted_output_cache", ["scope"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_scope"), "audit_events", ["scope"], unique=False)
    op.create_table(
        "billing_imports",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("dataset", sa.String(length=120), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("limit", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("reserved", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("spent", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.CheckConstraint("reserved >= 0 AND spent >= 0", name="ck_budget_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_sets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_change_sets_scope"), "change_sets", ["scope"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contracts_scope"), "contracts", ["scope"], unique=False)
    op.create_table(
        "billing_rows",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("import_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("service", sa.String(length=200), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billed", sa.Numeric(precision=32, scale=16), nullable=True),
        sa.Column("effective", sa.Numeric(precision=32, scale=16), nullable=True),
        sa.Column("raw_reference", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["billing_imports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "position", name="uq_billing_row_position"),
    )
    op.create_index(op.f("ix_billing_rows_import_id"), "billing_rows", ["import_id"], unique=False)
    op.create_table(
        "bundles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("contract_id", sa.String(length=64), nullable=False),
        sa.Column("change_id", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["change_id"],
            ["change_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(op.f("ix_bundles_scope"), "bundles", ["scope"], unique=False)
    op.create_table(
        "guard_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("contract_id", sa.String(length=64), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("bundle_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_bundle_id"), "evidence", ["bundle_id"], unique=False)
    op.create_index(op.f("ix_evidence_scope"), "evidence", ["scope"], unique=False)
    op.create_table(
        "review_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bundle_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("ai_preference", sa.String(length=16), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "idempotency_key", name="uq_review_idempotency"),
    )
    op.create_index("ix_job_claim", "review_jobs", ["state", "lease_until"], unique=False)
    op.create_index(op.f("ix_review_jobs_bundle_id"), "review_jobs", ["bundle_id"], unique=False)
    op.create_index(op.f("ix_review_jobs_scope"), "review_jobs", ["scope"], unique=False)
    op.create_table(
        "workload_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("bundle_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workload_runs_bundle_id"), "workload_runs", ["bundle_id"], unique=False
    )
    op.create_index(op.f("ix_workload_runs_scope"), "workload_runs", ["scope"], unique=False)
    op.create_table(
        "model_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_key", sa.String(length=100), nullable=False),
        sa.Column("budget_id", sa.String(length=200), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("reserved_cost", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("actual_cost", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_key"),
    )
    op.create_table(
        "review_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("core_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "core",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "explanation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["review_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_reports_outcome"), "review_reports", ["outcome"], unique=False)
    op.create_index(op.f("ix_review_reports_scope"), "review_reports", ["scope"], unique=False)
    op.create_table(
        "artifact_manifests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifact_manifests_review_id"), "artifact_manifests", ["review_id"], unique=False
    )
    op.create_table(
        "budget_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["model_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budget_ledger_attempt_id"), "budget_ledger", ["attempt_id"], unique=False
    )
    op.create_table(
        "guard_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column(
            "spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column(
            "fixture_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guard_drafts_review_id"), "guard_drafts", ["review_id"], unique=False)
    op.create_table(
        "outcomes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outcomes_review_id"), "outcomes", ["review_id"], unique=False)
    op.create_index(op.f("ix_outcomes_scope"), "outcomes", ["scope"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outcomes_scope"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_review_id"), table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index(op.f("ix_guard_drafts_review_id"), table_name="guard_drafts")
    op.drop_table("guard_drafts")
    op.drop_index(op.f("ix_budget_ledger_attempt_id"), table_name="budget_ledger")
    op.drop_table("budget_ledger")
    op.drop_index(op.f("ix_artifact_manifests_review_id"), table_name="artifact_manifests")
    op.drop_table("artifact_manifests")
    op.drop_index(op.f("ix_review_reports_scope"), table_name="review_reports")
    op.drop_index(op.f("ix_review_reports_outcome"), table_name="review_reports")
    op.drop_table("review_reports")
    op.drop_table("model_attempts")
    op.drop_index(op.f("ix_workload_runs_scope"), table_name="workload_runs")
    op.drop_index(op.f("ix_workload_runs_bundle_id"), table_name="workload_runs")
    op.drop_table("workload_runs")
    op.drop_index(op.f("ix_review_jobs_scope"), table_name="review_jobs")
    op.drop_index(op.f("ix_review_jobs_bundle_id"), table_name="review_jobs")
    op.drop_index("ix_job_claim", table_name="review_jobs")
    op.drop_table("review_jobs")
    op.drop_index(op.f("ix_evidence_scope"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_bundle_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("guard_revisions")
    op.drop_index(op.f("ix_bundles_scope"), table_name="bundles")
    op.drop_table("bundles")
    op.drop_index(op.f("ix_billing_rows_import_id"), table_name="billing_rows")
    op.drop_table("billing_rows")
    op.drop_index(op.f("ix_contracts_scope"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_change_sets_scope"), table_name="change_sets")
    op.drop_table("change_sets")
    op.drop_table("budgets")
    op.drop_table("billing_imports")
    op.drop_index(op.f("ix_audit_events_scope"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_accepted_output_cache_scope"), table_name="accepted_output_cache")
    op.drop_table("accepted_output_cache")
    # ### end Alembic commands ###
